//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesanan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pesanan()
        {
            this.barangs = new HashSet<barang>();
        }
    
        public string id_pesanan { get; set; }
        public string nomor_invoice { get; set; }
        public Nullable<int> jumlah_pesanan { get; set; }
        public Nullable<decimal> total_harga { get; set; }
        public Nullable<double> diskon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<barang> barangs { get; set; }
    }
}
